[project]
name = "idlspec2d"
version = "6.2.2dev"
description = "SDSS BOSS Data Reduction Pipeline"
readme = "README.md"
requires-python = ">=3.9,<3.12"
authors = [ {name = "Sean Morrison", email = "smorris0@illinois.edu"} ]
keywords = ["astronomy", "software", "pipeline"]
urls = { homepage = "https://github.com/sdss/idlspec2d", repository = "https://github.com/sdss/idlspec2d", documentation = "https://sdss-idlspec2d.readthedocs.org" }

dependencies = [
    "sdsstools>=1.9.4",
    "sdss-tree",
    "sdss-access",
    "sdss_semaphore>=0.2.8",
    "pydl>=1.0.0",
    "dustmaps>=v1.0.12",
    "PyAstronomy[occult]",
    "pyxcsao>=0.2",
    "numpy==1.26.4",
    "astropy>=6.0.0",
    "matplotlib>=3.8.3",
    "healpy>=1.16.6",
    "tqdm>=4.66.2",
    "pandas>=2.2.1",
    "h5py>=3.10.0",
    "scipy>=1.12.0",
    "pillow>=10.2.0",
    "jinja2",
    "termcolor>=2.4.0",
    "plotly>=5.22.0",
    "fitsio>=1.2.6",
    "psutil>=5.9.8",
    "GitPython>=3.1.44",
    "beautifulsoup4>=4.12.3",
    "pyarrow>=19.0.0",
    "polars",
    "VOparquet",
    "duckdb",
    "click",
    "ruamel.yaml",
    "keyring",
    "parse",
    "astro-pyvista",
]

[project.scripts]
boss_drp = "boss_drp.cli.BOSS_drp:cli"
SOS = "boss_drp.cli.SOS:cli"
boss_flatlib = "boss_drp.cli.flatlib:cli"
idlspec2d_version = "boss_drp.cli.boss_drp.version:version"
sdR_hdrfix = "boss_drp.cli.boss_drp.tools:run_sdR_hdrfix"
BOSS_log = "boss_drp.cli.SOS:run_log"

[project.optional-dependencies]
 utah = [
      "ipython", 
      "jupyterlab>=4.1.5",
      "sdssdb",
      "pgpasslib",
      "sqlalchemy==1.4.23",
      "flask==2.1.2",
      ]
 sdss_slurm = [
      "pgpasslib", 
      "sqlalchemy==1.4.23", 
      "flask==2.1.2", 
      "sdss-slurm", 
      "flask_sqlalchemy==2.5.1",
      "psycopg2",
      "werkzeug==2.0.1",
      ]
 sos = [
      "sdssdb",
      "ipython",
      ]
 docs = [
      "sphinx>=4.0.0",
      "sphinx-click>=2.6.0",
      "sphinx-jsonschema>=1.16.7",
      "myst-parser>=0.14.0",
      "furo>=2021.6.18-beta.36",
      "sphinx-autobuild>=2021.3.14",
      "sphinx-copybutton>=0.3.3",
      "sdss_access>=3.0.3",
      ]

[tool.uv.sources]
 sdssdb = [
     { path = '/home/sdss5/software/sdssdb/main/', editable = true, extra = 'sos'},
 ]
 
 sdss-slurm = [{git = 'ssh://git@github.com/sdss/slurm.git', branch = "main" }]
 astro-pyvista  = [{git = 'https://github.com/holtzmanjon/pyvista.git', tag = "0.4.3"}]
 PyAstronomy = [{git = 'https://github.com/sczesla/PyAstronomy.git', rev = "ed5065fe057364495f8df79c0a990aaf15d67414"}]

[tool.uv]
conflicts = [
    [
        { extra = "sos" },
        { extra = "utah" },
    ],
    [
        { extra = "sos" },
        { extra = "sdss_slurm" }
    ]
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# If you want to set package_dir mapping:
[tool.setuptools.package-dir]
"" = "python"

[tool.setuptools.packages.find]
where = ["python"]
include = ["boss_drp*"]

