key_match_dict=Dictionary($
         'NEXP',     'Number of Coadded Exposures',$
         'AZ',       'Azimuth axis pos. (approx, deg)',$
         'ALT',      'Altitude axis pos. (approx, deg)',$
         'AIRMASS',  'Mean airmass',$
         'TAIBEG',  'MJD(TAI) seconds at start of integrations',$
         'TAIEND',  'MJD(TAI) seconds at End of integrations',$
         'EXPTIME',  'Total Exposure time in seconds of integration',$
         'WTIME',    '',$
         'AIRTEMP',  '',$
         'CCDTEMP',  '',$
         'LN2TEMP',  '',$
         'DEWPOINT', '',$
         'DEWDEP',   '',$
         'DUSTA',    '',$
         'DUSTB',    '',$
         'DUSTC',    '',$
         'DUSTD',    '',$
         'GUSTS',    '',$
         'GUSTD',    '',$
         'HUMIDITY', '',$
         'HUMIDOUT', '',$
         'PRESSURE', '',$
         'WINDD',    '',$
         'WINDS',    '',$
         'WINDD25M', '',$
         'WINDS25M', '',$
         'TEMP01',   '',$
         'TEMP02',   '',$
         'TEMP03',   '',$
         'TEMP04',   '',$
         'HELIO_RV', 'Heliocentric correction (added to velocities)',$
         'NGUIDE',   'Number of guider frames during integration',$
         'SEEING20', '20% seeing during exposure (arcsec)',$
         'SEEING50', '50% seeing during exposure (arcsec)',$
         'SEEING80', '80% seeing during exposure (arcsec)',$
         'RMSOFF20', '20% RMS offset of guide fibers (arcsec)',$
         'RMSOFF50', '50% RMS offset of guide fibers (arcsec)',$
         'RMSOFF80', '80% RMS offset of guide fibers (arcsec)',$
         'XCHI2',    'Extraction: Mean chi^2',$
         'XCHI2MAX', 'Extraction: Maximum chi^2',$
         'XCHI2MIN', 'Extraction: Minimum chi^2',$
         'SKYCHI2',  'Mean chi^2 of sky-subtraction',$
         'SCHI2MAX', 'Maximim chi^2 of sky-subtraction',$
         'SCHI2MIN', 'Minimim chi^2 of sky-subtraction',$
         'WSIGMA',   '',$
         'WSIGMAX',  '',$
         'WSIGMIN',  '',$
         'XSIGMA',   '',$
         'XSIGMAX',  '',$
         'XSIGMIN',  ''$
         )


   
